import type { Metadata } from 'next';
import './globals.css';
import Providers from './providers';

const BASE_URL = 'https://www.wolfagroservices.com';

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  title: 'Wolf Agro Services – Fournisseur agro-export, Niger',
  description:
    'Sourcing direct, qualité contrôlée, logistique internationale. 800 tonnes exportées en 2025.',

  authors: [{ name: 'Wolf Agro Services' }],
  keywords: [
    'gomme arabique Niger',
    'sésame Niger',
    'oignon Galmi',
    'arachide décortiquée',
    'export agroalimentaire Niger',
    'agro-export Afrique',
    'fournisseur agricole Niger',
  ],

  // ── Open Graph ──────────────────────────────────────────────────────────
  openGraph: {
    type: 'website',
    url: BASE_URL,
    siteName: 'Wolf Agro Services',
    title: 'Wolf Agro Services – Fournisseur agro-export, Niger',
    description:
      'Sourcing direct, qualité contrôlée, logistique internationale. 800 tonnes exportées en 2025.',
    // /opengraph-image is auto-generated by src/app/opengraph-image.tsx (1200×630)
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'Wolf Agro Services – Fournisseur agro-export, Niger',
      },
    ],
    locale: 'fr_FR',
  },

  // ── Twitter / X Card ────────────────────────────────────────────────────
  twitter: {
    card: 'summary_large_image',
    title: 'Wolf Agro Services – Fournisseur agro-export, Niger',
    description:
      'Sourcing direct, qualité contrôlée, logistique internationale. 800 tonnes exportées en 2025.',
    images: ['/opengraph-image'],
  },

  // ── Favicon & icons ─────────────────────────────────────────────────────
  icons: {
    icon: '/lovable-uploads/logo.png',
    shortcut: '/lovable-uploads/logo.png',
    apple: '/lovable-uploads/logo.png',
  },

  // ── Canonical & verification ─────────────────────────────────────────────
  alternates: {
    canonical: BASE_URL,
  },
  verification: {
    google: '4rkY2ec33O59WK9g80XpOKNdyF3SoRBSDdUUEATrcrs',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Organization',
              name: 'Wolf Agro Services',
              url: BASE_URL,
              logo: `${BASE_URL}/lovable-uploads/logo.png`,
              email: 'contact@wolfagroservices.com',
              telephone: '+22720353509',
              address: {
                '@type': 'PostalAddress',
                streetAddress: 'Plateau',
                addressLocality: 'Niamey',
                addressCountry: 'NE',
              },
              description:
                "Fournisseur structuré à l'origine, spécialisé dans l'export de produits agricoles du Niger vers les marchés internationaux.",
              sameAs: ['https://www.facebook.com/wolfagroservices'],
            }),
          }}
        />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
